apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  rules:
    - host: {{ required "A valid .Values.host entry required!" .Values.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-http
              servicePort: http
