apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-smtp
  labels:
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 25
      targetPort: smtp
      protocol: TCP
      name: smtp
      nodePort: 30025
  selector:
    release: {{ .Release.Name }}
